### ISSUE TITLE
Seems to work fine for me

### ISSUE THREAD

**Issue by PineNappler** [vay3t/openvpn-pineapple#1]
![openvpn](https://user-images.githubusercontent.com/31130020/35112335-a3e12798-fc75-11e7-877d-97409f64cba9.png)

**Comment by PineNappler** [comment]
Ohhh you mean this? 
![openvpn1](https://user-images.githubusercontent.com/31130020/35112463-072e5032-fc76-11e7-9841-1089980691d7.png)

**Comment by PineNappler** [comment]
module.html -  seems pretty empty

**Comment by vay3t** [comment]
thx, fixed!
